Modify to re-run test in p.25
Error ouptput should like, because jsdom not exist

ReferenceError: document is not defined

  1 | describe("Appointment", () => {
  2 |   it("renders the customer first name", () => {
> 3 |	  expect(document.body.textContent).toMatch("Ashley");
    |            ^
  4 |   });
  5 | });
  6 |